# Generated by Django 2.1.7 on 2019-02-23 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190223_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='connections',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
