# Generated by Django 2.1.7 on 2019-02-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190223_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='party_tag',
            field=models.CharField(default='XXXXXXX', max_length=50),
        ),
    ]
