# Generated by Django 2.1.7 on 2019-02-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190224_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='category',
            field=models.CharField(default='Meetup', max_length=100),
        ),
        migrations.AddField(
            model_name='box',
            name='description',
            field=models.TextField(default='Come meet up, we are pretty awesome.'),
        ),
    ]
